package com.ats.dutyapp.adapter;

import android.content.Context;
import android.support.annotation.NonNull;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.ats.dutyapp.R;
import com.ats.dutyapp.model.MemoGenerated;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;


public class MemoGeneratedListAdapter extends RecyclerView.Adapter<MemoGeneratedListAdapter.MyViewHolder> {

    private ArrayList<MemoGenerated> memoList;
    private Context context;

    public MemoGeneratedListAdapter(ArrayList<MemoGenerated> memoList, Context context) {
        this.memoList = memoList;
        this.context = context;
    }


    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
        View itemView = LayoutInflater.from(viewGroup.getContext())
                .inflate(R.layout.adapter_memo_generated_list, viewGroup, false);

        return new MyViewHolder(itemView);
    }

    public class MyViewHolder extends RecyclerView.ViewHolder {

        private TextView tvHeader, tvDate,tvGeneratedBy,tvRemark;

        public MyViewHolder(@NonNull View itemView) {
            super(itemView);

            tvHeader = (itemView).findViewById(R.id.tvHeader);
            tvDate = (itemView).findViewById(R.id.tvDate);
            tvGeneratedBy = (itemView).findViewById(R.id.tvGeneratedBy);
            tvRemark = (itemView).findViewById(R.id.tvRemark);

        }
    }


    @Override
    public void onBindViewHolder(@NonNull MemoGeneratedListAdapter.MyViewHolder myViewHolder, int i) {

        MemoGenerated memo = memoList.get(i);

        SimpleDateFormat sdf1=new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat sdf2=new SimpleDateFormat("dd-MM-yyyy");

        try{

            Date d=sdf1.parse(memo.getMemoDate());
            String date=sdf2.format(d.getTime());

            myViewHolder.tvHeader.setText("" + memo.getHeaderName());
            myViewHolder.tvDate.setText("" + date);
            myViewHolder.tvGeneratedBy.setText("Generated By - " + memo.getGeneratedUserName());
            myViewHolder.tvRemark.setText("" + memo.getMemoDesc());

        }catch (Exception e){
            e.printStackTrace();
        }



    }

    @Override
    public int getItemCount() {
        return memoList.size();
    }
}
